### ISSUE TITLE
View of related documents

### ISSUE THREAD

**Issue by channingwalton** [SkepticMystic/adjacency-matrix-maker#1]
Would it be possible to provide a new view, linked to a document pane, of the most closely related documents?

It would be an interesting feature.

**Comment by SkepticMystic** [comment]
@channingwalton you might be interested in my [Graph Analysis plugin](https://github.com/SkepticMystic/graph-analysis). It is designed to shown "similar" notes

**Comment by channingwalton** [comment]
Awesome thank you!
