### ISSUE TITLE
[Feature Request] Show folder names in image

### ISSUE THREAD

**Issue by marcjulianschwarz** [SkepticMystic/adjacency-matrix-maker#3]
Hi @SkepticMystic!
First of all, I really enjoy using this plugin. It is always a joy to see the adjacency matrix of my vault.

Now to the feature request. I always have the option to show folders as squares enabled but I am having a hard time to differentiate the folders in the final image. Would it be possible to show a small text at each "folder square" (for example in the top left corner of the square) with the name of the corresponding folder? 
I guess with a high enough resolution set in the settings, the text should be readable (especially for the bigger squares with lots of notes in them).

Thank you,
Marc Julian

**Comment by SkepticMystic** [comment]
Hey Marc!
Sorry for not replying. I have been busy at work and with other plugins. You can leave this FR open, I'll always try get to it when I can. I quite like the idea you've proposed!

**Comment by marcjulianschwarz** [comment]
Hey @SkepticMystic!
No worries, I was just thinking about it for a bit and thought that it might not even be possible or the result might not look very good, especially because readability can’t be guaranteed for small folders with few notes in them. That’s why I closed the issue.

If you still like the FR, feel free to reopen it.

**Comment by SkepticMystic** [comment]
I'll see if I can find a good way to do it once I try :)
