### ISSUE TITLE
Feature request : Save adjacency matrix in a standard data table/format ?

### ISSUE THREAD

**Issue by daemuu** [SkepticMystic/adjacency-matrix-maker#4]
Hi SkepticMystic,

Recently, i runned a Google research with "adjacency matrix" and "Obsidian" as keywords, and naturally stumble on this plugin of yours, which i missed into the app plugin browser : Thanks for making this feature available, this is very interesting !

As i would need it quite soon in the near future, for professional foresight use, my initial research was to know if there would be a way to convert an Obsidian graph into an adjacency matrix.. but the latter one having numbers instead of colors :)

i.e. from something like this:

![Prospective Graphe](https://user-images.githubusercontent.com/30660422/149561168-577278f6-8ef8-4016-bab2-83e598e4c86f.jpeg)

to something like this:

![Prospective Table](https://user-images.githubusercontent.com/30660422/149561204-091f9874-4368-4bec-b02b-088a3a8274bf.jpeg)

Would you think this could be quite quickly implementable into the Save options of your plugin, like into .csv or some standard equivalent ??

Thanks for your feedback, and have a good One,

Damien

**Comment by SkepticMystic** [comment]
@woodoxherd hey :)
Here is a code snippet you can run in the Obsidian console.
It will create an adjacency matrix in JSON form:
```js
const { resolvedLinks } = app.metadataCache
const filePaths = Object.keys(resolvedLinks)
const adjMatrix = {}
filePaths.forEach(pathI => {
    adjMatrix[pathI] = {}
    filePaths.forEach(pathJ => {
        const degree = resolvedLinks[pathI][pathJ] ?? 0
        adjMatrix[pathI][pathJ] = degree
    })
})

console.log(JSON.stringify(adjMatrix)) 
```

**Comment by SkepticMystic** [comment]
You could then run that JSON object thru this converter to get it to CSV: https://www.convertcsv.com/json-to-csv.htm

**Comment by daemuu** [comment]
Hey @SkepticMystic !

I turned the example above as a new vault in order to try out your snippet, but it seems not to work, as you can see.

![Capture d’écran 2022-02-08 à 20 23 50](https://user-images.githubusercontent.com/30660422/153060579-c534b2cf-bc24-4043-b1fd-95dcc71e747f.png)

Maybe that is nothing, maybe i did something wrong ? 🤔
Anyway, i wonder where would be located the JSON object/file into my computer, so that i could process further into CSV convertion ?

**Comment by daemuu** [comment]
Here is the vault i used, in case you would need it for some debugging : [Adjacency Test.zip](https://github.com/SkepticMystic/adjacency-matrix-maker/files/8026880/Adjacency.Test.zip)

**Comment by SkepticMystic** [comment]
It looks like it ran fine the first time you called it. You can need to run `console.log(adjMatrix)` to print it to the console. Add that to the bottom of the snippet and run again.

But you'll see that calling it again will give the Duplicate Identifier error. That's because the snippet declares it's variables as `const`ants. So you can either reload Obsidian to wipe those away, or use `let` in place of const

**Comment by daemuu** [comment]
Ok Ross @SkepticMystic thanks, i think i managed my way out of this. \°/

So, for posterity, if ever someone with the same needs than me would land on this page, i used `console.log(JSON.stringify(adjMatrix))` into the console (instead of `console.log(adjMatrix)`), after running the snippet.

In our example, it returns some beautiful raw stuffs : 

> {"A.md":{"A.md":0,"B.md":1,"C.md":1,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":0},"B.md":{"A.md":0,"B.md":0,"C.md":1,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":1,"L.md":0,"M.md":0,"N.md":0},"C.md":{"A.md":0,"B.md":1,"C.md":0,"D.md":1,"E.md":0,"F.md":0,"G.md":1,"H.md":0,"I.md":1,"J.md":0,"K.md":1,"L.md":0,"M.md":0,"N.md":0},"D.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":1,"F.md":0,"G.md":1,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":0},"E.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":1,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":0},"F.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":1,"M.md":1,"N.md":0},"G.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":1,"F.md":1,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":0},"H.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":1,"J.md":0,"K.md":0,"L.md":0,"M.md":1,"N.md":1},"I.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":1,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":1,"N.md":1},"J.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":1,"H.md":0,"I.md":1,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":1},"K.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":1,"I.md":0,"J.md":1,"K.md":0,"L.md":0,"M.md":0,"N.md":0},"L.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":1,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":1},"M.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":1},"N.md":{"A.md":0,"B.md":0,"C.md":0,"D.md":0,"E.md":0,"F.md":0,"G.md":0,"H.md":0,"I.md":0,"J.md":0,"K.md":0,"L.md":0,"M.md":0,"N.md":0}}
> 

Then, just copy this output given by the console, and, after a slight move through [Regexr](https://regexr.com/ ) (for instance) in order to eliminate all the ".md", paste everything into the [ConvertCSV](https://www.convertcsv.com/json-to-csv.htm) mentioned above.

Et Voilà : [adjmatrixtest.csv](https://github.com/SkepticMystic/adjacency-matrix-maker/files/8032429/adjmatrixtest.csv) ! :)

**Comment by SkepticMystic** [comment]
Nice!
I've added that last little snippet of code to my original script, so it's all in one place :)

**Comment by daemuu** [comment]
@SkepticMystic 
A nice way to close the loop, i must say ! :)

Just as a an opening, a doorway : Would you have at your Knowledge some existing code already done that could process in the other way, i.e., starting from the CSV in order to build the Vault in Obsidian (with a template option, eventually) ??

As i intend to apply some matrix multiplication to the adjMatrix we got, that would be a convenient (and error less) way to vizualise the result back into Obsidian, compared to what i did by hand for our example above.

Please, let me know if ever you have references on this, please, and have a good One ! 🧐
